project_id=example-gcp-project
project_number=example-gcp-project-number
model_id=gemini-1.0-pro-001
embeddings_model_id=text-embedding-004
region=us-central1
index_id=example-index
index_id_name=semantic_cache
index_endpoint_id=example-id
index_endpoint_subdomain=example-subdomain
nearest_neighbor_min_distance=0.9
cache_entry_ttl_sec=60
use_cache=false