openapi: 3.0.0
info:
  title: Solar Panel Estimation API
  description: This API lets users get solar panel estimations based on their address.
  version: 1.0.0
paths:
  /estimations:
    get:
      description: Get a list of solar panel estimations for a given address.
      operationId: getEstimations
      parameters:
        - description: The number of items to return per API request.
          in: query
          name: pageSize
          schema:
            type: integer
        - description: >-
            A page token received from a previous API request, used to request a
            subsequent page.
          in: query
          name: pageToken
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Estimation'
                    type: array
                  nextPageToken:
                    type: string
                type: object
          description: A list of solar panel estimations.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error.
      tags:
        - estimations
    post:
      description: Creates a new solar panel estimation for a given address.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estimation'
          description: Estimation created successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error.
      summary: Create a new solar panel estimation for a given address.
      tags:
        - estimations
  /estimations/{estimationId}:
    delete:
      operationId: deleteEstimation
      responses:
        '204':
          description: No Content
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Estimation not found.
      summary: Delete a specific solar panel estimation.
      tags:
        - estimations
    get:
      description: Get the details of a specific solar panel estimation.
      operationId: getEstimationById
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estimation'
          description: OK
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
      tags:
        - estimations
    parameters:
      - description: The unique identifier of the estimation.
        in: path
        name: estimationId
        required: true
        schema:
          type: string
    put:
      description: Updates the details of a specific solar panel estimation.
      operationId: updateEstimation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Estimation'
        description: The updated estimation details.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estimation'
          description: The updated estimation details.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Estimation not found.
      summary: Update the details of a specific solar panel estimation.
      tags:
        - estimations
components:
  schemas:
    Address:
      description: The address of a location.
      properties:
        city:
          description: The city of the location.
          type: string
        state:
          description: The state of the location.
          type: string
        streetAddress:
          description: The street address of the location.
          type: string
        zipCode:
          description: The zip code of the location.
          type: string
      type: object
    Error:
      description: Error object
      properties:
        errorCode:
          description: The error code.
          type: string
        errorMessage:
          description: The error message.
          type: string
      type: object
    Estimation:
      description: >-
        An estimation of the cost and savings of installing solar panels at a
        specific location.
      properties:
        address:
          $ref: '#/components/schemas/Address'
        estimatedCost:
          description: The estimated cost of installing solar panels at the location.
          type: number
        estimatedSavings:
          description: >-
            The estimated savings on energy bills after installing solar panels
            at the location.
          type: number
        estimationId:
          description: The unique identifier of the estimation.
          type: string
      type: object
